sudo: required  # Needed to install a recent version of OpenJDK as well as Python 3.7

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env:
        TOXENV=py36
      before_install:
        - jdk_switcher use openjdk7
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env:
        TOXENV=py37
        JDK_SWITCH=openjdk8
      before_install:
        # xenial doesn't ship with jdk_switcher
        - wget https://raw.githubusercontent.com/michaelklishin/jdk_switcher/7e512921ba5a6e93ce304683f099e3c0525330b1/jdk_switcher.sh
        - source ./jdk_switcher.sh
        - jdk_switcher use openjdk8
        # Travis' xenial image hard-codes "openjdk11" into the path - if we want Java 8, we need to
        # manually insert it into the beginning of the path
        - export PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH"

install:
    - travis_retry pip install tox
script:
    - java -version
    - tox -e "$TOXENV"
    - if [[ $TOXENV == 'py36' ]] ; then tox -e py36-coveralls; else echo "No coverage to do"; fi
