language: python
python:
  - "3.5"

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
script:
    - tox -e py35
after_success:
    - tox -e py35-coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
